name: build

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Pull repo
      uses: actions/checkout@v1

    - name: build and push image
      run: |
        docker login docker.pkg.github.com --username ${{ secrets.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_PASSWORD }}
        docker build . --file Dockerfile --tag docker.pkg.github.com/kode-collektiv/frontend/frontend:latest
        docker push docker.pkg.github.com/kode-collektiv/frontend/frontend:latest
        
    - name: Pull docker images and restart container
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST_IP }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSPHRASE }}
        port: 22
        script: |
          docker login docker.pkg.github.com --username ${{ secrets.GITHUB_USERNAME }} --password ${{ secrets.GITHUB_PASSWORD }}
          docker-compose -f /srv/giessenteiltaus/docker-compose.yml pull
          docker-compose -f /srv/giessenteiltaus/docker-compose.yml rm --force
          docker-compose -f /srv/giessenteiltaus/docker-compose.yml up -d

      env:
        CI: true
